var val;
console.log(val);
val = "annyeong!";
console.log(val);
val = 1;
console.log(val);
val = true;
console.log(val);
val = undefined;
console.log(val);
val = [1, 2, 3];
console.log(val);
val = { name: "Ysrael" };
console.log(val);
val = null;
console.log(val);
val = Math.random();
console.log(val);
